export interface LessonMeta {
  slug: string;
  title: string;
  duration: string;
  order: number;
  description?: string;
}

export interface Course {
  slug: string;
  title: string;
  description: string;
  longDescription: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  duration: string;
  lessonCount: number;
  icon: string;
  color: string;
  badgeColor?: string;
  tags: string[];
  prerequisites: string[];
  learningObjectives: string[];
  lessons: LessonMeta[];
  featured: boolean;
  order: number;
  hasFullContent: boolean;
}


export const COURSES_MY: Course[] = [
  {
    slug: "linux-command-line",
    title: "DevOps အတွက် လင်းနပ်စ် (Linux) အမိန့်ပေးစာကြောင်း (Command Line)",
    description:
      "ဆာဗာများသို့ ယုံကြည်မှုရှိရှိ ဝင်ရောက်နိုင်ရန် တာမီနယ်၊ မရှိမဖြစ် ဘက်ရှ် (bash) အမိန့်ပေးချက်များ၊ ဖိုင်စီမံခန့်ခွဲမှု၊ ခွင့်ပြုချက်များ၊ လုပ်ငန်းစဉ် (process) စီမံခန့်ခွဲမှုနှင့် SSH တို့ကို ကျွမ်းကျင်ပိုင်နိုင်အောင် လေ့လာပါ။",
    longDescription:
      "လင်းနပ်စ် (Linux) သည် ခေတ်မီ DevOps ၏ ငြင်းမရသော လည်ပတ်မှုစနစ် (OS) တစ်ခု ဖြစ်ပါသည်။ ကွန်တိန်နာ (container) တိုင်း၊ ဗာတွယ်စက် (virtual machine) တိုင်း၊ ကလောက်ဆာဗာ (cloud server) တိုင်းနှင့် CI/CD ರrunner တိုင်းသည် Linux ပတ်ဝန်းကျင်တွင် လည်ပတ်ကြသည်။ ဤသင်တန်းတွင် သင်သည် Linux ကို အစမှစ၍ လက်တွေ့ကျကျ သင်ယူရမည်ဖြစ်သည် — ဖိုင်စနစ်အတွင်း သွားလာခြင်း၊ ခွင့်ပြုချက်များ စီမံခြင်း၊ လုပ်ငန်းစဉ်များကို စစ်ဆေးခြင်း၊ ကွန်ရက် ရောဂါရှာဖွေခြင်းနှင့် SSH မှတစ်ဆင့် အလုပ်လုပ်ခြင်းတို့ ပါဝင်သည်။",
    level: "Beginner",
    duration: "3.5 hours",
    lessonCount: 10,
    icon: "Terminal",
    color: "from-emerald-500 to-teal-600",
    tags: ["Linux", "Bash", "CLI", "SysAdmin", "Fundamentals"],
    prerequisites: [],
    learningObjectives: [
      "အဓိက သွားလာရေး အမိန့်ပေးချက်များ (pwd, ls, cd, history) ဖြင့် Linux ဖိုင်စနစ်အတွင်း လျင်မြန်စွာ သွားလာနိုင်ခြင်း",
      "ဖိုင်များနှင့် ဖိုင်တွဲများကို လုံခြုံစွာ ဖန်တီးခြင်း၊ စစ်ဆေးခြင်း၊ ပြုပြင်ခြင်းနှင့် စီမံခန့်ခွဲခြင်း",
      "grep, less, head, tail နှင့် find တို့ကို အသုံးပြု၍ လော့ဂ် (logs) များကို ဖတ်ရှုခြင်းနှင့် စနစ်စာသားများကို ရှာဖွေခြင်း",
      "ခွင့်ပြုချက်များ၊ ပိုင်ဆိုင်မှုများနှင့် chmod/chown ဂဏန်းနှင့် သင်္ကေတ ပုံစံများကို ကျွမ်းကျင်ပိုင်နိုင်ခြင်း",
      "ps, top, htop နှင့် kill တို့ဖြင့် စနစ်လုပ်ငန်းစဉ်များကို စစ်ဆေးခြင်း၊ စောင့်ကြည့်ခြင်းနှင့် ရပ်တန့်ခြင်း",
      "Debian/Ubuntu တွင် apt ဖြင့် ပက်ကေ့ဂျ်များကို ထည့်သွင်းခြင်းနှင့် စီမံခန့်ခွဲခြင်း",
      "curl, ping နှင့် ss တို့ဖြင့် ကွန်ရက် ချိတ်ဆက်မှုနှင့် နားထောင်နေသော ပေါ့တ် (ports) များကို ရောဂါရှာဖွေခြင်း",
      "SSH သော့များ ထုတ်လုပ်ခြင်းနှင့် အဝေးရောက် ဆာဗာများသို့ လုံခြုံစွာ ချိတ်ဆက်ခြင်း",
    ],
    lessons: [
      {
        slug: "01-why-linux-matters",
        title: "DevOps တွင် Linux အဘယ်ကြောင့် အရေးကြီးသနည်း",
        duration: "15 min",
        order: 1,
        description: "ကလောက် (cloud)၊ ကွန်တိန်နာများနှင့် DevOps ကိရိယာများကို Linux က မည်သို့ အဓိကမောင်းနှင်နေသည်ကို နားလည်ပါ။",
      },
      {
        slug: "02-terminal-basics",
        title: "တာမီနယ် အခြေခံများနှင့် သွားလာမှုများ",
        duration: "20 min",
        order: 2,
        description: "pwd, ls, cd, clear, history နှင့် အလိုအလျောက် ဖြည့်စွက်သည့် (autocomplete) အတိုကောက်များကို ကျွမ်းကျင်ပါ။",
      },
      {
        slug: "03-files-and-directories",
        title: "ဖိုင်များနှင့် ဖိုင်တွဲများဖြင့် အလုပ်လုပ်ခြင်း",
        duration: "25 min",
        order: 3,
        description: "ဖိုင်များနှင့် ဖိုင်တွဲများကို ဖန်တီးခြင်း၊ ရွှေ့ပြောင်းခြင်း၊ ကူးယူခြင်း၊ ဖျက်ဆီးခြင်းနှင့် လုံခြုံစွာ စစ်ဆေးခြင်း။",
      },
      {
        slug: "04-reading-editing-files",
        title: "ဖိုင်များ ဖတ်ရှုခြင်းနှင့် ပြုပြင်ခြင်း (nano, vim, grep)",
        duration: "25 min",
        order: 4,
        description: "nano/vim တွင် ကွန်ဖิกဖိုင်များကို ပြုပြင်ခြင်းနှင့် grep, find တို့ဖြင့် လော့ဂ်များကို အမြန်ရှာဖွေခြင်း။",
      },
      {
        slug: "05-permissions-ownership",
        title: "ခွင့်ပြုချက်များနှင့် ပိုင်ဆိုင်မှု (chmod, chown)",
        duration: "25 min",
        order: 5,
        description: "rwx ခွင့်ပြုချက် စာသားများ၊ ဂဏန်းသုံး chmod (755/644) နှင့် sudo အခွင့်အရေးများကို ဖတ်ရှုခွဲခြမ်းပါ။",
      },
      {
        slug: "06-process-management",
        title: "လုပ်ငန်းစဉ် စီမံခန့်ခွဲမှု (ps, top, kill)",
        duration: "20 min",
        order: 6,
        description: "CPU/memory သုံးစွဲနေမှုများကို စောင့်ကြည့်ခြင်း၊ နောက်ခံ အလုပ်များကို စစ်ဆေးခြင်းနှင့် လုပ်ငန်းစဉ်များကို ရပ်တန့်ခြင်း။",
      },
      {
        slug: "07-package-management",
        title: "apt ဖြင့် ပက်ကေ့ဂျ် စီမံခန့်ခွဲမှု",
        duration: "15 min",
        order: 7,
        description: "Ubuntu တွင် သိုလှောင်ရာများကို အပ်ဒိတ်လုပ်ခြင်း၊ ပက်ကေ့ဂျ်များ ထည့်သွင်းခြင်းနှင့် မှီခိုမှုများကို ရှင်းလင်းခြင်း။",
      },
      {
        slug: "08-networking-basics",
        title: "ကွန်ရက် အခြေခံများ (ping, curl, ss, ip)",
        duration: "25 min",
        order: 8,
        description: "နားထောင်နေသော ပေါ့တ်များကို စစ်ဆေးခြင်း၊ HTTP တောင်းဆိုချက်များ ပေးပို့ခြင်းနှင့် ကွန်ရက် ချိတ်ဆက်နိုင်မှုကို ဖြေရှင်းခြင်း။",
      },
      {
        slug: "09-ssh-and-servers",
        title: "SSH နှင့် အဝေးရောက် ဆာဗာများသို့ ချိတ်ဆက်ခြင်း",
        duration: "25 min",
        order: 9,
        description: "SSH သော့တွဲများ ထုတ်လုပ်ခြင်း၊ ssh config ကို ပြင်ဆင်ခြင်းနှင့် စကားဝှက်မလိုဘဲ ချိတ်ဆက်ခြင်း။",
      },
      {
        slug: "10-productivity-tips",
        title: "ထုတ်လုပ်မှုစွမ်းအား အကြံပြုချက်များ၊ ပိုက်လိုင်းများ၊ လမ်းကြောင်းပြောင်းခြင်းနှင့် အဖြစ်များသော အမှားများ",
        duration: "20 min",
        order: 10,
        description: "ပိုက်လိုင်းများ၊ လမ်းကြောင်းပြောင်းမှုများ (> နှင့် >>)၊ ယုတ္တိဗေဒ အော်ပရေတာများဖြင့် အမိန့်ပေးချက်များကို ပေါင်းစပ်ပြီး အစပြုသူတို့၏ ထောင်ချောက်များကို ရှောင်ကြဉ်ပါ။",
      },
    ],
    featured: true,
    order: 0,
    hasFullContent: true,
  },
  {
    slug: "git-github",
    title: "Git နှင့် GitHub အခြေခံများ",
    description:
      "ဗားရှင်း ထိန်းချုပ်မှုကို အစမှစ၍ လေ့လာပါ- staging၊ commits၊ branches၊ merges၊ remotes၊ pull requests နှင့် လက်တွေ့ကမ္ဘာ ဘာန်ချင်း (branching) မဟာဗျူဟာများ။",
    longDescription:
      "Git သည် ခေတ်မီဆော့ဖ်ဝဲ ပူးပေါင်းဆောင်ရွက်မှုနှင့် GitOps လုပ်ငန်းစဉ်များ၏ အခြေခံအုတ်မြစ် ဖြစ်ပါသည်။ ဤသင်တန်းတွင် သင်သည် Git က ပုံစံခွဲများကို မည်သို့ခြေရာခံသည်၊ ဘာ့ချ်များ မည်သို့ခွဲထွက်ပြီး ပြန်လည်ပေါင်းစည်းသည်၊ ကွဲလွဲမှုများကို မည်သို့လွယ်ကူစွာ ဖြေရှင်းရမည်၊ နှင့် GitHub Pull Requests နှင့် ကုဒ်သုံးသပ်ချက်များကို အသုံးပြု၍ မည်သို့ ပူးပေါင်းဆောင်ရွက်ရမည်ဆိုသည်ကို ခိုင်မာသော နားလည်မှု တည်ဆောက်နိုင်မည်ဖြစ်သည်။",
    level: "Beginner",
    duration: "3 hours",
    lessonCount: 8,
    icon: "GitBranch",
    color: "from-orange-500 to-amber-600",
    tags: ["Git", "GitHub", "VCS", "Collaboration", "GitFlow"],
    prerequisites: ["linux-command-line"],
    learningObjectives: [
      "ဖြန့်ဝေထားသော ဗားရှင်း ထိန်းချုပ်မှု သဘောတရားများနှင့် Git ၏ အတွင်းပိုင်း မော်ဒယ်များကို နားလည်ခြင်း",
      "သိုလှောင်ရာများကို စတင်ခြင်း၊ အပြောင်းအလဲများကို အဓိပ္ပါယ်ရှိရှိ စတိတ်တင်ခြင်းနှင့် သန့်ရှင်းသော ကွတ်မစ် (commit) စာသားများ ရေးသားခြင်း",
      "ဘာ့ချ်များကို ယုံကြည်မှုရှိရှိ ဖန်တီးခြင်း၊ ပြောင်းလဲခြင်းနှင့် ပေါင်းစပ်ခြင်း",
      "အဆင့်ဆင့် နည်းပညာများကို အသုံးပြု၍ ပေါင်းစပ်မှု ကွဲလွဲမှုများကို စိုးရိမ်ပူပန်မှုမရှိဘဲ ဖြေရှင်းခြင်း",
      "ဒေသတွင်း သိုလှောင်ရာများကို အဝေးရောက် GitHub သိုလှောင်ရာများနှင့် සමံကိုက်လုပ်ဆောင်ခြင်း (push, pull, fetch, clone)",
      "စက်မှုလုပ်ငန်း စံနှုန်းများနှင့်အညီ Pull Requests များကို ဖန်တီးခြင်း၊ သုံးသပ်ခြင်းနှင့် ပေါင်းစပ်ခြင်း",
      ".gitignore ဖိုင်များကို ပြင်ဆင်ခြင်းနှင့် atomic commits နှင့် conventional commit စံနှုန်းများကို အသုံးချခြင်း",
      "စစ်မှန်သော အသင်းအဖွဲ့များတွင် Git Flow နှင့် trunk-based ဖွံ့ဖြိုးတိုးတက်ရေး လုပ်ငန်းစဉ်များကို ကျင့်သုံးခြင်း",
    ],
    lessons: [
      {
        slug: "01-what-is-version-control",
        title: "ဗားရှင်း ထိန်းချုပ်မှုဆိုသည်မှာ အဘယ်နည်း။",
        duration: "15 min",
        order: 1,
        description: "ဗီဒီယိုဂိမ်း မှတ်တိုင် ဥပမာနှင့် ခေတ်မီ အင်ဂျင်နီယာပညာရပ်တွင် Git အဘယ်ကြောင့် လိုအပ်သနည်း။",
      },
      {
        slug: "02-installing-git",
        title: "Git ထည့်သွင်းခြင်းနှင့် ပထမဆုံး စနစ်ထည့်သွင်းမှု",
        duration: "15 min",
        order: 2,
        description: "OS ပလက်ဖောင်းအမျိုးမျိုးတွင် Git ကို ထည့်သွင်းပြီး အသုံးပြုသူအမည်၊ အီးမေးလ်နှင့် မူလဘာ့ချ်တို့ကို ပြင်ဆင်ပါ။",
      },
      {
        slug: "03-basic-git-workflow",
        title: "အခြေခံ Git လုပ်ငန်းစဉ် (init, add, commit)",
        duration: "25 min",
        order: 3,
        description: "အဆင့် ၃ ဆင့်ပါ သက်တမ်းစက်ဝန်းကို ကျွမ်းကျင်ပါ- Working Directory, Staging Area နှင့် Local Repository။",
      },
      {
        slug: "04-branching-and-merging",
        title: "ဘာ့ချ်ခွဲခြင်းနှင့် ပေါင်းစပ်ခြင်း (Branching & Merging)",
        duration: "30 min",
        order: 4,
        description: "အပြိုင် ဖွံ့ဖြိုးတိုးတက်မှုလမ်းကြောင်းများ ဖန်တီးပြီး fast-forward သို့မဟုတ် merge commits ဖြင့် ပြန်လည်ပေါင်းစပ်ပါ။",
      },
      {
        slug: "05-remote-repositories",
        title: "အဝေးရောက် သိုလှောင်ရာများနှင့် GitHub",
        duration: "25 min",
        order: 5,
        description: "သင့်ဒေသတွင်း Git သိုလှောင်ရာကို SSH မှတစ်ဆင့် GitHub သို့ ချိတ်ဆက်ပြီး ချောမွေ့စွာ push/pull လုပ်ပါ။",
      },
      {
        slug: "06-pull-requests",
        title: "Pull Requests နှင့် ကုဒ်သုံးသပ်ချက် (Code Review)",
        duration: "25 min",
        order: 6,
        description: "အပြောင်းအလဲများကို အဆိုပြုခြင်း၊ ကုဒ်သုံးသပ်ချက်များ ပြုလုပ်ခြင်း၊ တောင်းဆိုထားသော အပြောင်းအလဲများကို ဖြေရှင်းခြင်းနှင့် PR များကို လုံခြုံစွာ ပေါင်းစပ်ခြင်း။",
      },
      {
        slug: "07-git-best-practices",
        title: "Git အကောင်းဆုံး ကျင့်စဉ်များနှင့် .gitignore",
        duration: "20 min",
        order: 7,
        description: "conventional commits ရေးသားခြင်း၊ .gitignore ပြင်ဆင်ခြင်း၊ git stash အသုံးပြုခြင်းနှင့် ရှုပ်ထွေးသော မှတ်တမ်းများကို ရှောင်ကြဉ်ခြင်း။",
      },
      {
        slug: "08-real-world-workflow",
        title: "လက်တွေ့ကမ္ဘာ Git လုပ်ငန်းစဉ် (Git Flow နှင့် Trunk-Based)",
        duration: "25 min",
        order: 8,
        description: "Git Flow နှင့် Trunk-Based လုပ်ငန်းစဉ်များကို နှိုင်းယှဉ်ပြီး ထုတ်လုပ်မှုတွင် ထွက်ရှိမည့် ဘာ့ချ်ခွဲမှုကို နားလည်ပါ။",
      },
    ],
    featured: true,
    order: 1,
    hasFullContent: true,
  },
  {
    slug: "github-actions",
    title: "GitHub Actions အလိုအလျောက်လုပ်ဆောင်မှု",
    description:
      "Git ဖြစ်ရပ်များ (events) ကြောင့် တိုက်ရိုက်စတင်စေလွှတ်သော စာမ်းသပ်ခြင်း၊ linting၊ တည်ဆောက်ခြင်း၊ Docker ကွန်တိန်နာထုတ်ဝေခြင်းနှင့် ဖြန့်ချိရေး လုပ်ငန်းစဉ်များကို အလိုအလျောက်လုပ်ဆောင်ပါ။",
    longDescription:
      "GitHub Actions သည် GitHub တွင် တိုက်ရိုက်ပါရှိသော စက်မှုစံနှုန်း CI/CD ပလက်ဖောင်း ဖြစ်ပါသည်။ သင်သည် ရှင်းလင်းသော YAML လုပ်ငန်းစဉ်များကို ရေးသားခြင်း၊ pull requests သို့မဟုတ် tags များတွင် အလိုအလျောက်စနစ် စတင်ခြင်း၊ matrix builds များကို ပြင်ဆင်ခြင်း၊ ထိလွယ်ရှလွယ်သော രဟဿများကို လုံခြုံစေခြင်း၊ အလွန်မြန်ဆန်စွာ လည်ပတ်နိုင်ရန် မှီခိုမှုများကို cache လုပ်ခြင်းနှင့် အပလီကေးရှင်းများကို အလိုအလျောက် ဖြန့်ချိခြင်းတို့ကို သင်ယူရမည် ဖြစ်ပါသည်။",
    level: "Beginner",
    duration: "4 hours",
    lessonCount: 8,
    icon: "Zap",
    color: "from-indigo-500 to-violet-600",
    tags: ["CI/CD", "Automation", "GitHub Actions", "Workflows", "YAML"],
    prerequisites: ["linux-command-line", "git-github"],
    learningObjectives: [
      "CI/CD အဓိက သဘောတရားများနှင့် အလိုအလျောက် စီးပွားရေး စီးဆင်းမှုကို နားလည်ခြင်း",
      "သန့်ရှင်းပြီး အမှားအယွင်းကင်းသော GitHub Actions လုပ်ငန်းစဉ် YAML ဖိုင်များ ရေးသားခြင်း",
      "အစပျိုးမှုအမျိုးမျိုးကို ပြင်ဆင်ခြင်း: push, pull_request, schedule cron နှင့် လက်ဖြင့်ထုတ်လွှတ်ခြင်း",
      "needs မှီခိုမှုများကို အသုံးပြု၍ အပြိုင်နှင့် အစဉ်လိုက် လုပ်ငန်းများကို စီစဉ်ခြင်း",
      "လျှို့ဝှက်ချက်များ၊ အထောက်အထားများနှင့် ပတ်ဝန်းကျင် ကိန်းရှင်များကို လုံခြုံစွာ စီမံခန့်ခွဲခြင်း",
      "node_modules အတွက် caching ပါဝင်သော ပြီးပြည့်စုံသော အလိုအလျောက် စမ်းသပ်မှုနှင့် lint ပိုက်လိုင်း တည်ဆောက်ခြင်း",
      "Docker ရုပ်ပုံ (image) တည်ဆောက်ခြင်းနှင့် ကွန်တိန်နာ သိုလှောင်ရာများသို့ ပို့ဆောင်ခြင်းတို့ကို အလိုအလျောက်လုပ်ဆောင်ခြင်း",
      "လက်ဖြင့် အတည်ပြုခွင့်ပြုချက် စည်းမျဉ်းများပါရှိသော ထွက်ရှိမည့် ပတ်ဝန်းကျင်များကို အကောင်အထည်ဖော်ခြင်း",
    ],
    lessons: [
      {
        slug: "01-what-is-cicd",
        title: "CI/CD ဆိုသည်မှာ အဘယ်နည်း။",
        duration: "20 min",
        order: 1,
        description: "စက်ရုံလိုင်း ဥပမာများဖြင့် ရှင်းပြထားသော Continuous Integration နှင့် Continuous Delivery/Deployment။",
      },
      {
        slug: "02-github-actions-intro",
        title: "GitHub Actions နိဒါန်း",
        duration: "20 min",
        order: 2,
        description: "လုပ်ငန်းစဉ်များ၊ runner များ၊ အလုပ်များ၊ အဆင့်များ၊ နှင့် အသိုင်းအဝိုင်း စျေးကွက်လုပ်ဆောင်ချက်များကို ခွဲခြမ်းစိတ်ဖြာပါ။",
      },
      {
        slug: "03-workflow-syntax",
        title: "လုပ်ငန်းစဉ် YAML သတ်ပုံ (Syntax) ခွဲခြမ်းစိတ်ဖြာခြင်း",
        duration: "30 min",
        order: 3,
        description: "မရှိမဖြစ် YAML သော့ချက်များအားလုံးကို ကျွမ်းကျင်ပါ: name, on, jobs, runs-on, steps, uses, run နှင့် with။",
      },
      {
        slug: "04-triggers-and-events",
        title: "စတင်စပြုမှုများ၊ စစ်ထုတ်မှုများနှင့် ဖြစ်ရပ်များ",
        duration: "25 min",
        order: 25,
        description: "push, pull_request, လမ်းကြောင်းစစ်ထုတ်မှုများ (src/**)၊ cron အချိန်ဇယားများနှင့် ထည့်သွင်းမှုများတွင် ပိုက်လိုင်းများကို စတင်ပါ။",
      },
      {
        slug: "05-jobs-and-steps",
        title: "အလုပ်များ၊ အဆင့်များ၊ မှီခိုမှုများနှင့် Matrix တည်ဆောက်မှုများ",
        duration: "30 min",
        order: 5,
        description: "အလုပ်များကို တစ်ပြိုင်နက် လုပ်ဆောင်ခြင်း၊ needs ဖြင့် အစဉ်လိုက် ချိတ်ဆက်ခြင်းနှင့် Node/OS ဗားရှင်းများစွာတွင် စမ်းသပ်ခြင်း။",
      },
      {
        slug: "06-environment-variables",
        title: "လျှို့ဝှက်ချက်များ၊ ကိန်းရှင်များနှင့် ဆက်စပ်မှုများ",
        duration: "25 min",
        order: 6,
        description: "GitHub Secrets၊ သိုလှောင်ရာ ကိန်းရှင်များ၊ GITHUB_SHA ဆက်စပ်မှုများကို ထည့်သွင်းခြင်းနှင့် ထိလွယ်ရှလွယ်သော တိုကင်များကို ဖုံးအုပ်ခြင်း။",
      },
      {
        slug: "07-build-test-workflow",
        title: "အမှန်တကယ် တည်ဆောက်ခြင်းနှင့် စမ်းသပ်ခြင်း လုပ်ငန်းစဉ် တည်ဆောက်ခြင်း",
        duration: "35 min",
        order: 7,
        description: "အဆင့်ဆင့်: checkout, setup Node.js, cache dependencies, run ESLint နှင့် execute test suites။",
      },
      {
        slug: "08-deploy-workflow",
        title: "စဉ်ဆက်မပြတ် ဖြန့်ချိရေး ပိုက်လိုင်း (Continuous Deployment Pipeline)",
        duration: "35 min",
        order: 8,
        description: "GitHub Pages သို့ အလိုအလျောက် တည်ငြိမ်သော ဆိုက်ဖြန့်ချိခြင်းနှင့် SSH ဖြင့် ဆာဗာဖြန့်ချိခြင်းများကို အလိုအလျောက်လုပ်ဆောင်ပါ။",
      },
    ],
    featured: true,
    order: 2,
    hasFullContent: true,
  },
  {
    slug: "cicd-concepts",
    title: "CI/CD ပိုက်လိုင်း သဘောတရားများနှင့် ဗိသုကာ (Architecture)",
    description:
      "ပိုက်လိုင်း ဗိသုကာများ၊ ဖန်တီးထားသော ပစ္စည်းများ (artifacts)၊ တည်ဆောက်ရေး အေးဂျင့်များ၊ အလိုအလျောက် စမ်းသပ်မှု ပိရမစ်များ၊ ရပ်တန့်ချိန်မရှိသော မဟာဗျူဟာများနှင့် canary rollouts များကို အသေးစိတ် လေ့လာပါ။",
    longDescription:
      "အလိုအလျောက် စနစ်ကို မချဲ့ထွင်မီ DevOps အင်ဂျင်နီယာတိုင်းသည် ခိုင်မာသော CI/CD စနစ်များ၏ နောက်ကွယ်ရှိ အဓိက ဗိသုကာ ပုံစံများကို နားလည်ရမည်ဖြစ်သည်- ပစ္စည်း မှတ်ပုံတင်များ (artifact registries)၊ ယာယီ စမ်းသပ် ပတ်ဝန်းကျင်များ၊ blue-green ဖြန့်ချိမှုများ၊ canary rollouts များနှင့် ဘေးအန္တရာယ် ကာကွယ်ရေး ပြန်လည်ပြင်ဆင်မှု (rollback) မဟာဗျူဟာများ။",
    level: "Intermediate",
    duration: "3 hours",
    lessonCount: 6,
    icon: "Workflow",
    color: "from-blue-500 to-cyan-600",
    tags: ["CI/CD", "Architecture", "Deployment", "BestPractices"],
    prerequisites: ["github-actions"],
    learningObjectives: [
      "စမ်းသပ်မှု ပိရမစ် (Unit, Integration, E2E) နှင့် အလိုအလျောက် အတားအဆီးများကို ကျွမ်းကျင်ပိုင်နိုင်ခြင်း",
      "မပြောင်းလဲနိုင်သော ပစ္စည်းများနှင့် မူလအစကို နားလည်ခြင်း",
      "Blue-Green, Rolling နှင့် Canary ဖြန့်ချိရေး မဟာဗျူဟာများကို နှိုင်းယှဉ်ခြင်း",
      "အလိုအလျောက် ပြန်လည်ပြင်ဆင်ခြင်း (rollback) နှင့် ဓာတုကျန်းမာရေး စစ်ဆေးမှုများကို အကောင်အထည်ဖော်ခြင်း",
    ],
    lessons: [
      { slug: "01-pipeline-stages", title: "ခေတ်မီ ပိုက်လိုင်းတစ်ခု၏ ခန္ဓာဗေဒ", duration: "25 min", order: 1 },
      { slug: "02-artifact-management", title: "ပစ္စည်းများ၊ မှတ်ပုံတင်များနှင့် မပြောင်းလဲနိုင်ခြင်း", duration: "25 min", order: 2 },
      { slug: "03-testing-gates", title: "အလိုအလျောက် အရည်အသွေး တံခါးပေါက်များနှင့် လုံခြုံရေး စကင်ဖတ်ခြင်း", duration: "30 min", order: 3 },
      { slug: "04-deployment-strategies", title: "Blue-Green, Canary နှင့် Rolling အပ်ဒိတ်များ", duration: "35 min", order: 4 },
      { slug: "05-observability-in-cicd", title: "ပိုက်လိုင်း တိုင်းတာမှုများ၊ MTTR နှင့် DORA တိုင်းတာမှုများ", duration: "25 min", order: 5 },
      { slug: "06-disaster-recovery", title: "ပြန်လည်ပြင်ဆင်ရေး မဟာဗျူဟာများနှင့် ဖြစ်ရပ် အလိုအလျောက်လုပ်ဆောင်မှု", duration: "30 min", order: 6 },
    ],
    featured: false,
    order: 3,
    hasFullContent: true,
  },
  {
    slug: "docker-fundamentals",
    title: "ਡocker နှင့် ကွန်တိန်နာ အခြေခံများ",
    description:
      "အပလီကေးရှင်းများကို ပေါ့ပါးပြီး ပြန်လည်ထုတ်လုပ်နိုင်သော ကွန်တိန်နာများအဖြစ် ထုပ်ပိုးပါ။ Dockerfile ညွှန်ကြားချက်များ၊ အလွှာ cache လုပ်ခြင်း၊ ရုပ်ပုံ အကောင်းဆုံးဖြစ်အောင်လုပ်ခြင်းနှင့် volume mounts များကို ကျွမ်းကျင်ပါ။",
    longDescription:
      "ကွန်တိန်နာများသည် ဂန္ထဝင်ပြဿနာဖြစ်သော 'ကျွန်တော့်စက်ထဲမှာတော့ အလုပ်လုပ်တယ်' ဆိုသည့် ပြဿနာကို ထာဝရ ဖြေရှင်းပေးခဲ့သည်။ ဤသင်တန်းတွင် သင်သည် ကွန်တိန်နာ ဗာတွယ်လိုက်ဇေးရှင်းနှင့် ဗီအမ် (VMs) ကို နားလည်ခြင်း၊ ထုတ်လုပ်မှုအတွက် အသင့်ဖြစ်သော အဆင့်ဆင့် Dockerfiles များကို ရေးသားခြင်း၊ ကွန်တိန်နာ တိုက်ခိုက်ခံရနိုင်ခြေကို လျှော့ချခြင်း၊ ဒေတာများကို volumes ဖြင့် စီမံခန့်ခွဲခြင်းနှင့် ကွန်တိန်နာများကို စိတ်ကြိုက်ကွန်ရက်များဖြင့် ချိတ်ဆက်ခြင်းတို့ကို သင်ယူရမည် ဖြစ်ပါသည်။",
    level: "Intermediate",
    duration: "5 hours",
    lessonCount: 10,
    icon: "Box",
    color: "from-sky-500 to-blue-600",
    tags: ["Docker", "Containers", "DevOps", "Images", "Virtualization"],
    prerequisites: ["linux-command-line", "git-github"],
    learningObjectives: [
      "ကွန်တိန်နာ ဗိသုကာကို နားလည်ခြင်း: namespaces, cgroups နှင့် container runtimes",
      "ရုပ်ပုံ အရွယ်အစားကို ၈၀% ကျော် လျှော့ချပေးသော အဆင့်ဆင့် (multi-stage) Dockerfiles များကို ရေးသားခြင်း",
      "Docker Volumes နှင့် Bind Mounts ကို အသုံးပြု၍ ဒေတာဘေ့စ်နှင့် အပလီကေးရှင်း သိုလှောင်မှုကို ဆက်လက်ထိန်းသိမ်းခြင်း",
      "သီးခြားခွဲထားသော ကွန်တိန်နာများကို bridge နှင့် overlay ကွန်ရက်များဖြင့် ချိတ်ဆက်ခြင်း",
    ],
    lessons: [
      { slug: "01-containers-vs-vms", title: "ကွန်တိန်နာများနှင့် ဗာတွယ်စက်များ (Virtual Machines)", duration: "25 min", order: 1 },
      { slug: "02-docker-architecture", title: "Docker Engine, Daemon နှင့် Registry ဗိသုကာ", duration: "25 min", order: 2 },
      { slug: "03-running-first-container", title: "သင့်ပထမဆုံး ကွန်တိန်နာကို လည်ပတ်ခြင်း (docker run, exec, logs)", duration: "30 min", order: 3 },
      { slug: "04-writing-dockerfiles", title: "သန့်ရှင်းသော Dockerfiles ရေးသားခြင်း (FROM, RUN, COPY, CMD)", duration: "35 min", order: 4 },
      { slug: "05-layer-caching", title: "Docker အလွှာ Cache လုပ်ခြင်းနှင့် တည်ဆောက်မှု အကောင်းဆုံးဖြစ်အောင်လုပ်ခြင်း", duration: "30 min", order: 5 },
      { slug: "06-multi-stage-builds", title: "အနည်းဆုံး ထုတ်လုပ်မှု ရုပ်ပုံများအတွက် အဆင့်ဆင့် တည်ဆောက်မှုများ", duration: "35 min", order: 6 },
      { slug: "07-volumes-and-storage", title: "Volumes, Bind Mounts နှင့် တည်မြဲသော ဒေတာများ", duration: "30 min", order: 7 },
      { slug: "08-container-networking", title: "ကွန်တိန်နာ ကွန်ရက်ချိတ်ဆက်မှုနှင့် Port Forwarding", duration: "30 min", order: 8 },
      { slug: "09-docker-hub-registries", title: "Docker Hub နှင့် GitHub GHCR သို့ ရုပ်ပုံများ ပို့ဆောင်ခြင်း", duration: "25 min", order: 9 },
      { slug: "10-security-best-practices", title: "Non-Root အသုံးပြုသူများ၊ စကင်ဖတ်ခြင်းနှင့် ကွန်တိန်နာ လုံခြုံရေးမြှင့်တင်ခြင်း", duration: "30 min", order: 10 },
    ],
    featured: true,
    order: 4,
    hasFullContent: true,
  },
  {
    slug: "docker-compose",
    title: "Docker Compose နှင့် ကွန်တိန်နာမျိုးစုံ အပလီကေးရှင်းများ",
    description:
      "ရှင်းလင်းသော YAML ကွန်ဖิกဖိုင်များဖြင့် အဆင့်ဆင့် ဝက်ဘ်အပလီကေးရှင်းများ (Next.js, Node.js API, PostgreSQL, Redis) ကို စီစဉ်ညှိနှိုင်းပါ။",
    longDescription:
      "စစ်မှန်သော အပလီကေးရှင်းများသည် အပြန်အလှန် အလုပ်လုပ်သော ဝန်ဆောင်မှုများစွာဖြင့် ဖွဲ့စည်းထားပါသည်- ဖရန့်အန်းဒ် (frontend)၊ ဘက်အန်းဒ် API၊ ဒေတာဘေ့စ်နှင့် မှတ်ဉာဏ်တွင်း ကက်ရှ် (in-memory cache)။ Docker Compose သည် အပလီကေးရှင်း စတပ်စ် (stacks) တစ်ခုလုံးကို အမိန့်ပေးချက်တစ်ခုတည်းဖြင့် သတ်မှတ်ခြင်း၊ စတင်ခြင်းနှင့် ကွန်ရက်ချိတ်ဆက်ခြင်းတို့ကို ပြုလုပ်နိုင်စေပါသည်။",
    level: "Intermediate",
    duration: "3 hours",
    lessonCount: 6,
    icon: "Layers",
    color: "from-cyan-500 to-teal-600",
    tags: ["Docker Compose", "Multi-Tier", "Databases", "Networking"],
    prerequisites: ["docker-fundamentals"],
    learningObjectives: [
      "ပတ်ဝန်းကျင် ကိန်းရှင်များနှင့် ကျန်းမာရေး စစ်ဆေးမှုများပါရှိသော ဝန်ဆောင်မှုမျိုးစုံပါသော docker-compose.yml ဖိုင်များကို ရေးသားခြင်း",
      "ဖရန့်အန်းဒ်များ၊ API များနှင့် ဒေတာဘေ့စ်များကို ချောမွေ့စွာ ကွန်ရက်ချိတ်ဆက်ခြင်း",
      "Compose တွင် လျوဖ့်ဝှက်ချက်များနှင့် ဒေတာဘေ့စ် စတင်ရေး စာမူများကို စီမံခန့်ခွဲခြင်း",
    ],
    lessons: [
      { slug: "01-why-docker-compose", title: "Docker Compose အဘယ်ကြောင့် လိုအပ်သနည်း။", duration: "20 min", order: 1 },
      { slug: "02-compose-file-structure", title: "Compose YAML သတ်မှတ်ချက် (services, networks, volumes)", duration: "30 min", order: 2 },
      { slug: "03-building-fullstack-app", title: "Web App + Postgres + Redis ကို ပေါင်းစပ်လည်ပတ်ခြင်း", duration: "40 min", order: 3 },
      { slug: "04-environment-variables", title: "ပတ်ဝန်းကျင် ကွန်ဖิกနှင့် .env ဖိုင်များ", duration: "25 min", order: 4 },
      { slug: "05-service-dependencies", title: "ကျန်းမာရေး စစ်ဆေးမှုများနှင့် depends_on အခြေအနေများ", duration: "30 min", order: 5 },
      { slug: "06-compose-production", title: "ဖွံ့ဖြိုးတိုးတက်မှုနှင့် ထုတ်လုပ်မှုတွင် Docker Compose", duration: "25 min", order: 6 },
    ],
    featured: false,
    order: 5,
    hasFullContent: true,
  },
  {
    slug: "kubernetes-basics",
    title: "ኩဘာနက်တစ် (Kubernetes - K8s) အခြေခံများ",
    description:
      "စံလုပ်ငန်းသုံး ကွန်တိန်နာ စီစဉ်ညှိနှိုင်းရေးစနစ်သို့ ဝင်ရောက်ပါ: Pods, Deployments, Services, ConfigMaps, Ingress နှင့် ကိုယ်တိုင်ကုစားနိုင်သော စနစ်များ။",
    longDescription:
      "Kubernetes သည် ကမ္ဘာ့အဆင့်စကေးတွင် ကွန်တိန်နာသုံး အပလီကေးရှင်းများ၏ ဖြန့်ချိခြင်း၊ ချဲ့ထွင်ခြင်းနှင့် စီမံခန့်ခွဲခြင်းတို့ကို အလိုအလျောက်လုပ်ဆောင်ပေးပါသည်။ ဤသင်တန်းသည် သင့်အား K8s ဗိသုကာအတွင်းသို့ ခေါ်ဆောင်သွားမည် ဖြစ်သည်- Control Plane အစိတ်အပိုင်းများ၊ Worker Nodes, Pod သက်တမ်းစက်ဝန်းများ၊ ရှင်းလင်းသော YAML ဖော်ပြချက်များနှင့် ကလပ်စတာ ဝန်ဆောင်မှု ရှာဖွေတွေ့ရှိမှု။",
    level: "Intermediate",
    duration: "6 hours",
    lessonCount: 12,
    icon: "Compass",
    color: "from-blue-600 to-indigo-700",
    tags: ["Kubernetes", "K8s", "Orchestration", "CloudNative", "Pods"],
    prerequisites: ["docker-fundamentals", "docker-compose"],
    learningObjectives: [
      "Control Plane (API Server, etcd, Scheduler) နှင့် Worker Node (kubelet, kube-proxy) ဗိသုကာကို နားလည်ခြင်း",
      "Pods, ReplicaSets နှင့် Deployments များအတွက် ရှင်းလင်းသော ဖော်ပြချက်များကို ရေးသားခြင်းနှင့် အသုံးချခြင်း",
      "ClusterIP, NodePort နှင့် LoadBalancer Services များဖြင့် လုပ်ငန်းများကို ဖော်ထုတ်ပြသခြင်း",
      "ConfigMaps နှင့် K8s Secrets များဖြင့် အပလီကေးရှင်း ကွန်ဖิกများကို စီမံခန့်ခွဲခြင်း",
    ],
    lessons: [
      { slug: "01-why-kubernetes", title: "Kubernetes အဘယ်ကြောင့် လိုအပ်သနည်း။ စီစဉ်ညှိနှိုင်းမှု ရှင်းလင်းချက်", duration: "25 min", order: 1 },
      { slug: "02-k8s-architecture", title: "Control Plane နှင့် Worker Node ဗိသုကာ", duration: "30 min", order: 2 },
      { slug: "03-kubectl-cli", title: "kubectl CLI: အမိန့်ပေးချက်များ၊ အခြေအနေများနှင့် နာမည်နေရာများ", duration: "30 min", order: 3 },
      { slug: "04-pods", title: "Pods ကို နားလည်ခြင်း: အသေးငယ်ဆုံး ဖြန့်ချိနိုင်သော ယူနစ်", duration: "25 min", order: 4 },
      { slug: "05-deployments-replicasets", title: "Deployments နှင့် ReplicaSets: ကိုယ်တိုင်ကုစားခြင်းနှင့် ချဲ့ထွင်ခြင်း", duration: "35 min", order: 5 },
      { slug: "06-services-networking", title: "ဝန်ဆောင်မှုများနှင့် ကွန်ရက်ချိတ်ဆက်မှု: ClusterIP, NodePort, LoadBalancer", duration: "35 min", order: 6 },
      { slug: "07-configmaps-secrets", title: "ConfigMaps နှင့် Secrets: ကွန်ဖิกများကို ခွဲထုတ်ခြင်း", duration: "30 min", order: 7 },
      { slug: "08-ingress-controllers", title: "Ingress Controllers နှင့် HTTP လမ်းကြောင်းပြောင်းခြင်း", duration: "35 min", order: 8 },
      { slug: "09-resource-limits", title: "CPU နှင့် Memory အရင်းအမြစ် တောင်းဆိုမှုများနှင့် ကန့်သတ်ချက်များ", duration: "25 min", order: 9 },
      { slug: "10-liveness-readiness", title: "Liveness, Readiness နှင့် Startup ကျန်းမာရေး စစ်ဆေးမှုများ", duration: "30 min", order: 10 },
      { slug: "11-storage-pv-pvc", title: "Persistent Volumes (PV) နှင့် PVC တောင်းဆိုမှုများ", duration: "35 min", order: 11 },
      { slug: "12-rolling-updates", title: "ရပ်တန့်ချိန်မရှိသော Rolling အပ်ဒိတ်များနှင့် ပြန်လည်ပြင်ဆင်မှုများ", duration: "30 min", order: 12 },
    ],
    featured: true,
    order: 6,
    hasFullContent: true,
  },
  {
    slug: "k3s",
    title: "K3s: ပေါ့ပါးသော Kubernetes",
    description:
      "တစ်ကိုယ်ရေ VPS nodes များ၊ အစွန်းစက်ပစ္စည်းများ (edge devices)၊ ဒေသတွင်း ဖွံ့ဖြိုးတိုးတက်မှုနှင့် သေးငယ်သော ထုတ်လုပ်မှု ကလပ်စတာများတွင် ပေါ့ပါးပြီး စံကိုက်ညီသော Kubernetes ကို လည်ပတ်ပါ။",
    longDescription:
      "K3s သည် Rancher မှ ဖန်တီးထားသော အသိအမှတ်ပြုလက်မှတ်ရ၊ ပေါ့ပါးသော Kubernetes ဖြန့်ချိမှုတစ်ခု ဖြစ်သည်။ ရှေးဟောင်း ကလောက် ပံ့ပိုးပေးသူများကို ဖယ်ရှားပြီး <70MB ရှိသော ဘိုင်နရီ တစ်ခုတည်းအဖြစ် ထုပ်ပိုးထားကာ ၎င်းသည် သင်ယူမှု၊ VPS ဆာဗာများ၊ အိမ်သုံး လက်ပ်များနှင့် အစွန်းရောက် ဖြန့်ချိမှုများအတွက် စံပြ Kubernetes ပလက်ဖောင်း ဖြစ်ပါသည်။",
    level: "Intermediate",
    duration: "4 hours",
    lessonCount: 8,
    icon: "Cpu",
    color: "from-yellow-500 to-amber-600",
    tags: ["K3s", "Rancher", "EdgeK8s", "Lightweight", "VPS"],
    prerequisites: ["linux-command-line", "kubernetes-basics"],
    learningObjectives: [
      "စက္ကန့် ၃၀ အတွင်း Linux ဆာဗာ တစ်ခုတည်းတွင် K3s ကို ထည့်သွင်းခြင်း",
      "K3s ရှိ မြှုပ်နှံထားသော SQLite နှင့် etcd သိုလှောင်ရေး အင်ဂျင်များကို နားလည်ခြင်း",
      "K3s တွင် ပါရှိသော Traefik ingress ဖြင့် ကွန်တိန်နာသုံး အပလီကေးရှင်းများကို ဖြန့်ချိခြင်း",
      "cert-manager နှင့် Let's Encrypt တို့ဖြင့် TLS လက်မှတ်များကို အလိုအလျောက် စီမံခန့်ခွဲခြင်း",
    ],
    lessons: [
      { slug: "01-what-is-k3s", title: "K3s ဆိုသည်မှာ အဘယ်နည်း၊ ၎င်းကို အဘယ်ကြောင့် အသုံးပြုသင့်သနည်း။", duration: "25 min", order: 1 },
      { slug: "02-installing-k3s", title: "အမိန့်ပေးချက် တစ်ခုတည်းဖြင့် Linux / VPS တွင် K3s ထည့်သွင်းခြင်း", duration: "25 min", order: 2 },
      { slug: "03-traefik-ingress", title: "ပါရှိပြီးသား Traefik Ingress Controller", duration: "30 min", order: 3 },
      { slug: "04-deploying-apps-k3s", title: "K3s သို့ Full-Stack အပလီကေးရှင်းများ ဖြန့်ချိခြင်း", duration: "35 min", order: 4 },
      { slug: "05-cert-manager-tls", title: "cert-manager နှင့် Let's Encrypt ဖြင့် အလိုအလျောက် HTTPS", duration: "35 min", order: 5 },
      { slug: "06-multi-node-cluster", title: "Node များစွာပါသော ကလပ်စတာတစ်ခု ဖြစ်လာစေရန် Worker Nodes များ ထည့်သွင်းခြင်း", duration: "30 min", order: 6 },
      { slug: "07-k3s-backup-restore", title: "အရန်သိမ်းဆည်းမှုများ၊ ပုံဖမ်းဆီးမှုများ (snapshots) နှင့် ဘေးအန္တရာယ် ပြန်လည်ထူထောင်ရေး", duration: "30 min", order: 7 },
      { slug: "08-monitoring-k3s", title: "Prometheus နှင့် Grafana ဖြင့် ကလပ်စတာ စောင့်ကြည့်ခြင်း", duration: "35 min", order: 8 },
    ],
    featured: false,
    order: 7,
    hasFullContent: true,
  },
  {
    slug: "terraform-iac",
    title: "Terraform နှင့် အခြေခံအဆောက်အအုံ ကုဒ်အဖြစ် (Infrastructure as Code - IaC)",
    description:
      "ရှင်းလင်းသော အခြေခံအဆောက်အအုံ အလိုအလျောက်စနစ်ကို ကျွမ်းကျင်ပိုင်နိုင်ပါ: HCL သတ်ပုံ၊ ပံ့ပိုးပေးသူများ (providers)၊ စတိတ် လော့ခ်ချခြင်း (state locking)၊ ပြန်သုံးနိုင်သော မော်ဂျူးများ၊ ပတ်ဝန်းကျင်မျိုးစုံ စနစ်ထည့်သွင်းမှုများနှင့် CI/CD plan/apply လုပ်ငန်းစဉ်များ။",
    longDescription:
      "ခေတ်မီ ကလောက် အခြေခံအဆောက်အအုံကို ဝက်ဘ် ကွန်ဆိုးလ်များမှတစ်ဆင့် လက်ဖြင့် ကွန်ဖิกလုပ်၍မရပါ။ Terraform ဖြင့် အခြေခံအဆောက်အအုံကို ကုဒ်အဖြစ် (IaC) ပြုလုပ်ခြင်းက အလိုအလျောက်၊ ဗားရှင်း ထိန်းချုပ်ထားသော၊ ပြန်လည်ထုတ်လုပ်နိုင်သော ကလောက် ဗိသုကာများကို ဖန်တီးပေးနိုင်ပါသည်။ ဤသင်တန်းတွင် သင်သည် HashiCorp ကွန်ဖิกဘာသာစကား (HCL)၊ အဝေးရောက် ဘက်အန်းဒ်များဖြင့် စတိတ်ကို လုံခြုံစွာ စီမံခန့်ခွဲခြင်း၊ မော်ဂျူးကုဒ်များ ရေးသားခြင်း၊ ကွန်ဖิก ကွဲလွဲမှုကို ကိုင်တွယ်ခြင်းနှင့် ဖြန့်ချိရေး ပိုက်လိုင်းများကို အလိုအလျောက်လုပ်ဆောင်ခြင်းတို့ကို သင်ယူရမည် ဖြစ်ပါသည်။",
    level: "Intermediate",
    duration: "4.5 hours",
    lessonCount: 8,
    icon: "Boxes",
    color: "from-purple-600 to-indigo-600",
    tags: ["Terraform", "IaC", "Cloud", "HCL", "Automation"],
    prerequisites: ["linux-command-line", "git-github"],
    learningObjectives: [
      "ကုဒ်အဖြစ် အခြေခံအဆောက်အအုံ၏ အကျိုးကျေးဇူးများနှင့် ရှင်းလင်းသော အရင်းအမြစ် စီမံခန့်ခွဲမှုကို နားလည်ခြင်း",
      "ကိန်းရှင်များ၊ အထွက်များနှင့် ဒေသခံများပါရှိသော သန့်ရှင်းသော HashiCorp ကွန်ဖิกဘာသာစကား (HCL) ကို ရေးသားခြင်း",
      "ကလောက်နှင့် ဒေသတွင်း ဟိုက်ပါဗိုင်ဇာများအတွက် ပံ့ပိုးပေးသူများကို ပြင်ဆင်ခြင်း",
      "AWS S3 နှင့် DynamoDB စတိတ် လော့ခ်ချခြင်းကို အသုံးပြု၍ အဝေးရောက် စတိတ်ကို လုံခြုံစွာ စီမံခန့်ခွဲခြင်း",
      "ထည့်သွင်းမှုများနှင့် အတည်ပြုချက်များပါရှိသော ထိန်းသိမ်းနိုင်သော၊ ပြန်သုံးနိုင်သော အခြေခံအဆောက်အအုံ မော်ဂျူးများကို ဖွဲ့စည်းခြင်း",
      "terraform refresh နှင့် import တို့ဖြင့် အခြေခံအဆောက်အအုံ ကွဲလွဲမှုကို ရှာဖွေပြီး ဖြေရှင်းခြင်း",
      "GitHub Actions CI/CD လုပ်ငန်းစဉ်များအတွင်း terraform plan & apply ကို အလိုအလျောက်လုပ်ဆောင်ခြင်း",
    ],
    lessons: [
      { slug: "01-what-is-iac", title: "ကုဒ်အဖြစ် အခြေခံအဆောက်အအုံနှင့် Terraform ဗိသုကာ အဘယ်ကြောင့် လိုအပ်သနည်း။", duration: "25 min", order: 1 },
      { slug: "02-hcl-syntax-providers", title: "HCL သတ်ပုံ၊ ပံ့ပိုးပေးသူများနှင့် အဓိက အရင်းအမြစ် တုံးများ (Resource Blocks)", duration: "30 min", order: 2 },
      { slug: "03-variables-outputs", title: "ထည့်သွင်းမှု ကိန်းရှင်များ၊ ဒေသခံများနှင့် အထွက် တန်ဖိုးများ", duration: "30 min", order: 3 },
      { slug: "04-state-management", title: "Terraform စတိတ်၊ အဝေးရောက် S3 ဘက်အန်းဒ်နှင့် စတိတ် လော့ခ်ချခြင်း", duration: "35 min", order: 4 },
      { slug: "05-reusable-modules", title: "ပြန်သုံးနိုင်သော၊ ထုတ်လုပ်မှုအဆင့်ရှိ အခြေခံအဆောက်အအုံ မော်ဂျူးများ ဖန်တီးခြင်း", duration: "35 min", order: 5 },
      { slug: "06-environments-workspaces", title: "ပတ်ဝန်းကျင်မျိုးစုံ စတပ်စ်များ (Dev/Staging/Prod) နှင့် လုပ်ငန်းခွင်များ", duration: "30 min", order: 6 },
      { slug: "07-drift-and-import", title: "ကွဲလွဲမှု ရှာဖွေခြင်း၊ စတိတ် အသစ်ပြန်လည်လုပ်ဆောင်ခြင်းနှင့် အရင်းအမြစ်များ တင်သွင်းခြင်း", duration: "35 min", order: 7 },
      { slug: "08-automated-iac-pipeline", title: "GitHub Actions တွင် အလိုအလျောက် Terraform Plan & Apply", duration: "40 min", order: 8 },
    ],
    featured: true,
    order: 8,
    hasFullContent: true,
  },
  {
    slug: "monitoring-observability",
    title: "Prometheus, Grafana နှင့် ကလောက် စောင့်ကြည့်လေ့လာနိုင်မှု (Observability)",
    description:
      "ထုတ်လုပ်မှု မြင်သာမှုကို တည်ဆောက်ပါ: စောင့်ကြည့်လေ့လာနိုင်မှု၏ တိုင် ၃ ခု (တိုင်းတာမှုများ၊ လော့ဂ်များ၊ ခြေရာခံမှုများ)၊ PromQL မေးမြန်းချက်များ၊ Node Exporter, Grafana ဒက်ရှ်ဘုတ်များ၊ Loki လော့ဂ် စုစည်းမှုနှင့် Alertmanager။",
    longDescription:
      "သင်မမြင်နိုင်သည်ကို သင်ပြင်၍မရပါ။ ခေတ်မီ ဖြန့်ဝေထားသော စနစ်များသည် အပြည့်အစုံ စောင့်ကြည့်လေ့လာနိုင်မှု (observability) လိုအပ်ပါသည်။ ဤသင်တန်းတွင် သင်သည် Prometheus တိုင်းတာမှု စုဆောင်းခြင်းနှင့် PromQL မေးမြန်းမှု ဘာသာစကားကို ကျွမ်းကျင်ပိုင်နိုင်ခြင်း၊ Grafana တွင် အမှုဆောင်နှင့် အင်ဂျင်နီယာ ဒက်ရှ်ဘုတ်များ တည်ဆောက်ခြင်း၊ Promtail နှင့် Loki တို့ဖြင့် ကွန်တိန်နာ လော့ဂ်များကို စုစည်းခြင်းနှင့် Alertmanager ဖြင့် လုပ်ဆောင်နိုင်သော သတိပေးချက် လမ်းကြောင်းများကို ပြင်ဆင်ခြင်းတို့ကို သင်ယူရမည် ဖြစ်ပါသည်။",
    level: "Intermediate",
    duration: "4.5 hours",
    lessonCount: 8,
    icon: "LineChart",
    color: "from-orange-500 to-rose-600",
    tags: ["Prometheus", "Grafana", "Loki", "Observability", "PromQL"],
    prerequisites: ["linux-command-line", "docker-fundamentals"],
    learningObjectives: [
      "စောင့်ကြည့်လေ့လာနိုင်မှု၏ တိုင် ၃ ခုကို နားလည်ခြင်း: Metrics, Logs နှင့် Distributed Traces",
      "Prometheus ဆာဗာ စုဆောင်းရေး ပစ်မှတ်များနှင့် အိတ်စပို့ထ်လုပ်သူများကို ထည့်သွင်းခြင်းနှင့် ပြင်ဆင်ခြင်း",
      "CPU၊ memory၊ အမှားအယွင်းနှုန်းများနှင့် 99 ရာခိုင်နှုန်းစုအတွက် လက်တွေ့ကမ္ဘာ PromQL ဖော်မြူလာများကို ရေးသားခြင်း",
      "အလိုအလျောက် အပ်ဒိတ်လုပ်ခြင်းနှင့် ကိန်းရှင်များပါရှိသော Grafana တွင် အပြန်အလှန် အကျိုးသက်ရောက်မှုရှိသော ဒက်ရှ်ဘုတ်များ တည်ဆောက်ခြင်း",
      "Grafana Loki နှင့် Promtail ကို အသုံးပြု၍ ကွန်တိန်နာနှင့် စနစ် လော့ဂ်များကို စုစည်းခြင်း",
      "Alertmanager လမ်းကြောင်းပြောင်းခြင်း၊ ပုံတူပွားမှုကို ဖယ်ရှားခြင်းနှင့် Slack/Discord အသိပေးချက်များကို ပြင်ဆင်ခြင်း",
      "ဖြန့်ဝေထားသော ခြေရာခံခြင်း သဘောတရားများနှင့် OpenTelemetry တူရိယာတပ်ဆင်ခြင်းကို နားလည်ခြင်း",
    ],
    lessons: [
      { slug: "01-observability-pillars", title: "စောင့်ကြည့်လေ့လာနိုင်မှု၏ တိုင် ၃ ခု (Metrics, Logs, Traces)", duration: "25 min", order: 1 },
      { slug: "02-prometheus-architecture", title: "Prometheus ဗိသုကာ၊ စုဆောင်းခြင်းနှင့် အချိန်တန်း စာရင်းအင်း ဒေတာဘေ့စ် (TSDB)", duration: "30 min", order: 2 },
      { slug: "03-promql-mastery", title: "PromQL ကျွမ်းကျင်ပိုင်နိုင်မှု: Rates, Histograms နှင့် Quantiles", duration: "35 min", order: 3 },
      { slug: "04-node-exporter-cAdvisor", title: "စနစ်နှင့် ကွန်တိန်နာ အိတ်စပို့ထ်လုပ်သူများ (Node Exporter, cAdvisor)", duration: "30 min", order: 4 },
      { slug: "05-grafana-dashboards", title: "Grafana တွင် ထိရောက်မှုမြင့်မားသော ဒက်ရှ်ဘုတ်များ ဒီဇိုင်းဆွဲခြင်း", duration: "35 min", order: 5 },
      { slug: "06-loki-log-aggregation", title: "Loki နှင့် Promtail ဖြင့် ဗဟိုချုပ်ကိုင်ထားသော ကွန်တိန်နာ လော့ဂ်လုပ်ခြင်း", duration: "35 min", order: 6 },
      { slug: "07-alertmanager-alerts", title: "Alertmanager: သတိပေးချက် စည်းမျဉ်းများ၊ ပုံတူပွားမှု ဖယ်ရှားခြင်းနှင့် Slack လမ်းကြောင်းပြောင်းခြင်း", duration: "35 min", order: 7 },
      { slug: "08-opentelemetry-tracing", title: "OpenTelemetry ဖြင့် ဖြန့်ဝေထားသော ခြေရာခံခြင်း အခြေခံများ", duration: "35 min", order: 8 },
    ],
    featured: true,
    order: 9,
    hasFullContent: true,
  },
  {
    slug: "devsecops-hardening",
    title: "DevSecOps နှင့် ကလောက် လုံခြုံရေးမြှင့်တင်ခြင်း (Cloud Security Hardening)",
    description:
      "အဆင့်တိုင်းတွင် လုံခြုံရေးကို ထည့်သွင်းပါ: Shift-left တည်ငြိမ်သော ခွဲခြမ်းစိတ်ဖြာမှု၊ Trivy ဖြင့် ကွန်တိန်နာ ရုပ်ပုံ ထိခိုက်လွယ်မှု စကင်ဖတ်ခြင်း၊ Cosign ဖြင့် ရုပ်ပုံ လက်မှတ်ထိုးခြင်း၊ လျှို့ဝှက်ချက် စီမံခန့်ခွဲမှုနှင့် K8s လုံခြုံရေး။",
    longDescription:
      "လုံခြုံရေးသည် နောက်မှ စဉ်းစားရမည့်အရာ သို့မဟုတ် အတားအဆီးတစ်ခု မဟုတ်ပါ — ၎င်းသည် အလိုအလျောက် အရည်အသွေး တံခါးပေါက်တစ်ခု ဖြစ်ပါသည်။ ဤသင်တန်းတွင် သင်သည် DevSecOps ကျင့်စဉ်များကို ကျွမ်းကျင်ပိုင်နိုင်မည် ဖြစ်သည်- CI/CD တွင် ထိခိုက်လွယ်မှုများနှင့် ပေါက်ကြားသွားသော အထောက်အထားများအတွက် ကုဒ်ကို စကင်ဖတ်ခြင်း၊ Trivy ဖြင့် ကွန်တိန်နာ အခြေခံ ရုပ်ပုံများကို စကင်ဖတ်ခြင်း၊ Sigstore Cosign ဖြင့် မပြောင်းလဲနိုင်သော ကွန်တိန်နာ ပစ္စည်းများကို လက်မှတ်ထိုးခြင်း၊ HashiCorp Vault ဖြင့် လျှို့ဝှက်ချက်များကို စီမံခန့်ခွဲခြင်းနှင့် RBAC နှင့် NetworkPolicies တို့ဖြင့် Kubernetes ကို လုံခြုံအောင် မြှင့်တင်ခြင်း။",
    level: "Intermediate",
    duration: "4.5 hours",
    lessonCount: 8,
    icon: "ShieldAlert",
    color: "from-rose-500 to-red-700",
    tags: ["DevSecOps", "Security", "Trivy", "Cosign", "Hardening"],
    prerequisites: ["linux-command-line", "github-actions", "docker-fundamentals"],
    learningObjectives: [
      "Shift-Left လုံခြုံရေး መርတ္တရားများနှင့် DevSecOps သက်တမ်းစက်ဝန်းကို နားလည်ခြင်း",
      "CI/CD ပိုက်လိုင်းများတွင် အလိုအလျောက် SAST နှင့် လျှို့ဝှက်ချက် ပေါက်ကြားမှု ရှာဖွေခြင်း (Gitleaks, Semgrep) ကို လုပ်ဆောင်ခြင်း",
      "Trivy ဖြင့် CVE ထိခိုက်လွယ်မှုများအတွက် ကွန်တိန်နာ ရုပ်ပုံများကို စကင်ဖတ်ပြီး အရေးကြီးသော အမှားများတွင် တည်ဆောက်မှုကို ရပ်တန့်ခြင်း",
      "Sigstore Cosign ကို အသုံးပြု၍ ကွန်တိန်နာ ရုပ်ပုံများကို ဒစ်ဂျစ်တယ်စနစ်ဖြင့် လက်မှတ်ထိုးခြင်းနှင့် အတည်ပြုခြင်း",
      "ကုဒ်အတွင်း တိုက်ရိုက်ထည့်သွင်းခြင်း (hardcoding) သို့မဟုတ် ပုံမှန်စာသား ပေါ်လွင်ခြင်းမရှိဘဲ လျှို့ဝှက်ချက်များကို လုံခြုံစွာ သိမ်းဆည်းခြင်းနှင့် ထည့်သွင်းခြင်း",
      "လင်းနပ်စ် ဆာဗာများကို လုံခြုံအောင် မြှင့်တင်ခြင်း: non-root အသုံးပြုသူများ၊ SSH သော့ အတည်ပြုခြင်းနှင့် UFW မီးသီး စည်းမျဉ်းများ",
      "RBAC၊ ServiceAccounts နှင့် NetworkPolicies တို့ဖြင့် Kubernetes တွင် အနည်းဆုံးအခွင့်အရေး (least-privilege) ဝင်ရောက်မှုကို အတင်းအကျပ် လုပ်ဆောင်ခြင်း",
    ],
    lessons: [
      { slug: "01-shift-left-security", title: "Shift-Left လုံခြုံရေးနှင့် DevSecOps စိတ်ဓာတ်", duration: "25 min", order: 1 },
      { slug: "02-static-analysis-sast", title: "CI/CD တွင် အလိုအလျောက် SAST နှင့် လျှို့ဝှက်ချက် ပေါက်ကြားမှု စကင်ဖတ်ခြင်း", duration: "30 min", order: 2 },
      { slug: "03-vulnerability-scanning-trivy", title: "Trivy ဖြင့် ကွန်တိန်နာနှင့် ဖိုင်စနစ် CVE စကင်ဖတ်ခြင်း", duration: "35 min", order: 3 },
      { slug: "04-container-signing-cosign", title: "ထောက်ပံ့ရေးကွင်းဆက် လုံခြုံရေး: Cosign ဖြင့် ရုပ်ပုံများ လက်မှတ်ထိုးခြင်း", duration: "35 min", order: 4 },
      { slug: "05-secret-management", title: "HashiCorp Vault နှင့် Sealed Secrets ဖြင့် လျှို့ဝှက်ချက် စီမံခန့်ခွဲမှု", duration: "35 min", order: 5 },
      { slug: "06-linux-hardening-ssh", title: "လင်းနပ်စ် ဆာဗာ လုံခြုံရေးမြှင့်တင်ခြင်း၊ မီးနံရံများ (Firewalls) နှင့် Non-Root ကွန်တိန်နာများ", duration: "35 min", order: 6 },
      { slug: "07-kubernetes-rbac-networkpolicies", title: "Kubernetes လုံခြုံရေး: RBAC, ServiceAccounts နှင့် NetworkPolicies", duration: "40 min", order: 7 },
      { slug: "08-runtime-security-falco", title: "Falco ဖြင့် အချိန်နှင့်တပြေးညီ ခြိမ်းခြောက်မှု ရှာဖွေခြင်းနှင့် စာရင်းစစ်ခြင်း (Auditing)", duration: "35 min", order: 8 },
    ],
    featured: true,
    order: 10,
    hasFullContent: true,
  },
  {
    slug: "gitops-argocd",
    title: "ArgoCD ဖြင့် GitOps နှင့် စဉ်ဆက်မပြတ် ဖြန့်ချိမှု (Continuous Delivery)",
    description:
      "ခေတ်မီ ရှင်းလင်းသော GitOps လုပ်ငန်းစဉ်များကို လက်ခံကျင့်သုံးပါ: ArgoCD ဗိသုကာ၊ အပလီကေးရှင်း CRD များ၊ အလိုအလျောက် repo စင့်ခ်လုပ်ခြင်း (syncing)၊ Kustomize overlays၊ Helm charts နှင့် တိုးတက်သော Canary ဖြန့်ချိမှု။",
    longDescription:
      "GitOps သည် Git သည် တစ်ခုတည်းသော အမှန်တရား၏ ရင်းမြစ်ဖြစ်သော Kubernetes ဖြန့်ချိမှုအတွက် ခေတ်မီ ရွှေစံနှုန်းကို ကိုယ်စားပြုပါသည်။ ဤသင်တန်းတွင် သင်သည် ArgoCD ကို ထည့်သွင်းပြီး ပြင်ဆင်ခြင်း၊ စိတ်ကြိုက် အရင်းအမြစ် အဓိပ္ပါယ်ဖွင့်ဆိုချက်များ (Custom Resource Definitions) ဖြင့် အပလီကေးရှင်းများကို ရှင်းလင်းစွာ ကြေညာခြင်း၊ Kustomize နှင့် Helm ကို အသုံးပြု၍ ပတ်ဝန်းကျင်မျိုးစုံ ဖော်ပြချက်များကို စီမံခန့်ခွဲခြင်း၊ အလိုအလျောက် ကွဲလွဲမှု ရှာဖွေခြင်းနှင့် ကိုယ်တိုင်ကုစားခြင်းကို အတင်းအကျပ် လုပ်ဆောင်ခြင်းနှင့် Argo Rollouts ဖြင့် တိုးတက်သော Canary rollouts များကို လုပ်ဆောင်ခြင်းတို့ကို သင်ယူရမည် ဖြစ်ပါသည်။",
    level: "Advanced",
    duration: "5 hours",
    lessonCount: 8,
    icon: "Boxes",
    color: "from-cyan-500 to-blue-600",
    tags: ["GitOps", "ArgoCD", "Kubernetes", "Kustomize", "ContinuousDelivery"],
    prerequisites: ["git-github", "kubernetes-basics", "k3s"],
    learningObjectives: [
      "GitOps အဓိက မူဘောင်များကို နားလည်ခြင်း: ရှင်းလင်းသော အခြေအနေ၊ ဗားရှင်း ထိန်းချုပ်မှု၊ အလိုအလျောက် ဆွဲယူ စင့်ခ်လုပ်ခြင်း",
      "CLI နှင့် Web UI ဝင်ရောက်ခွင့်ဖြင့် Kubernetes တွင် ArgoCD ကို ထည့်သွင်းခြင်းနှင့် ပြင်ဆင်ခြင်း",
      "Application နှင့် ApplicationSet Custom Resource Definitions (CRDs) ကို အသုံးပြု၍ အပလီကေးရှင်းများကို သတ်မှတ်ခြင်း",
      "Kustomize overlays နှင့် Helm ပါရာမီတာများဖြင့် ပတ်ဝန်းကျင် ကျော်လွန်မှုများကို သန့်ရှင်းစွာ စီမံခန့်ခွဲခြင်း",
      "အလိုအလျောက် စင့်ခ် မူဝါဒများ၊ ဖျက်ဆီးထားသော အရင်းအမြစ်များကို ရှင်းလင်းခြင်းနှင့် ကလပ်စတာ ကိုယ်တိုင်ကုစားခြင်းကို ဖွင့်လှစ်ခြင်း",
      "Argo Rollouts ဖြင့် ရပ်တန့်ချိန်မရှိသော Canary နှင့် Blue-Green ဖြန့်ချိမှုများကို လုပ်ဆောင်ခြင်း",
    ],
    lessons: [
      { slug: "01-gitops-principles", title: "GitOps အဓိက မူဘောင်များနှင့် ရှင်းလင်းသော စဉ်ဆက်မပြတ် ဖြန့်ချိမှု", duration: "25 min", order: 1 },
      { slug: "02-argocd-architecture", title: "ArgoCD ဗိသုကာ၊ ထည့်သွင်းခြင်းနှင့် Web UI လည်ပတ်မှု", duration: "30 min", order: 2 },
      { slug: "03-declarative-apps-crd", title: "ရှင်းလင်းသော အပလီကေးရှင်းများ: Application CRDs နှင့် Git Repos", duration: "35 min", order: 3 },
      { slug: "04-kustomize-helm-gitops", title: "Kustomize နှင့် Helm ဖြင့် ပတ်ဝန်းကျင်မျိုးစုံ ဖော်ပြချက်များကို စီမံခန့်ခွဲခြင်း", duration: "35 min", order: 4 },
      { slug: "05-sync-strategies-drift", title: "စင့်ခ် မူဝါဒများ: အလိုအလျောက် စင့်ခ်၊ ရှင်းလင်းခြင်းနှင့် ကိုယ်တိုင်ကုစားခြင်း", duration: "35 min", order: 5 },
      { slug: "06-app-of-apps-pattern", title: "App-of-Apps ပုံစံနှင့် ကလပ်စတာမျိုးစုံ ဖြန့်ချိမှုများ", duration: "35 min", order: 6 },
      { slug: "07-progressive-delivery-rollouts", title: "Argo Rollouts ဖြင့် တိုးတက်သော ဖြန့်ချိမှု (Canary နှင့် Blue-Green)", duration: "40 min", order: 7 },
      { slug: "08-production-gitops-workflow", title: "ထုတ်လုပ်မှု GitOps ဗိသုကာနှင့် ဘေးအန္တရာယ် ပြန်လည်ထူထောင်ရေး", duration: "35 min", order: 8 },
    ],
    featured: true,
    order: 11,
    hasFullContent: true,
  },
  {
    slug: "cicd-project",
    title: "အပြည့်အစုံ လက်တွေ့ကမ္ဘာ CI/CD ပိုက်လိုင်း ပရောဂျက်",
    description:
      "Capstone: Git + GitHub Actions + Docker + GHCR + K3s Kubernetes တို့ကို အလိုအလျောက် GitOps ထုတ်လုပ်မှု ဖြန့်ချိမှုတစ်ခုအဖြစ် ချိတ်ဆက်ပါ။",
    longDescription:
      "သင်၏ ကျွမ်းကျင်မှုအားလုံးကို အစွန်းတစ်ဖက်မှ အစွန်းတစ်ဖက်သို့ (end-to-end) ပြီးပြည့်စုံသော ပရောဂျက်တစ်ခုတွင် စုစည်းပါ။ သင်သည် Next.js ထုတ်လုပ်မှု ဝက်ဘ်အပလီကေးရှင်းတစ်ခု တည်ဆောက်ခြင်း၊ အဆင့်ဆင့် Dockerfiles များကို ရေးသားခြင်း၊ GitHub Actions CI/CD ကို ပြင်ဆင်ခြင်းဖြင့် ရုပ်ပုံများကို GitHub Container Registry သို့ တည်ဆောက်ပြီး ပို့ဆောင်ခြင်း၊ နှင့် ရပ်တန့်ချိန်မရှိသော အလိုအလျောက် rollouts များဖြင့် တိုက်ရိုက် K3s ကလပ်စတာသို့ အပ်ဒိတ်များကို လုံခြုံစွာ ဖြန့်ချိခြင်းတို့ကို လုပ်ဆောင်ရမည် ဖြစ်ပါသည်။",
    level: "Advanced",
    duration: "6 hours",
    lessonCount: 10,
    icon: "Trophy",
    color: "from-emerald-500 to-indigo-600",
    tags: ["Capstone", "EndToEnd", "GitOps", "Production", "ZeroDowntime"],
    prerequisites: ["linux-command-line", "git-github", "github-actions", "docker-fundamentals", "k3s"],
    learningObjectives: [
      "အစမှစ၍ ပြီးပြည့်စုံသော၊ အလိုအလျောက် အစွန်းတစ်ဖက်မှ အစွန်းတစ်ဖက်သို့ DevOps ပိုက်လိုင်းတစ်ခုကို ဗိသုကာပြုလုပ်ခြင်း",
      "ရုပ်ပုံ တည်ဆောက်ခြင်း၊ Trivy ဖြင့် စကင်ဖတ်ခြင်းနှင့် GHCR သို့ ထုတ်ဝေခြင်းတို့ကို အလိုအလျောက်လုပ်ဆောင်ခြင်း",
      "K3s Kubernetes ကလပ်စတာများသို့ လုံခြုံသော SSH မလိုသော GitOps ဖြန့်ချိမှုကို အကောင်အထည်ဖော်ခြင်း",
      "အလိုအလျောက် မီးခိုး စမ်းသပ်မှု (smoke testing) နှင့် rolling update အတည်ပြုချက်များကို ပြင်ဆင်ခြင်း",
    ],
    lessons: [
      { slug: "01-project-architecture", title: "ပရောဂျက် ပုံစံနှင့် စနစ် ဗိသုကာ", duration: "30 min", order: 1 },
      { slug: "02-sample-app-setup", title: "ထုတ်လုပ်မှု Next.js + DB အပလီကေးရှင်းကို စနစ်ထည့်သွင်းခြင်း", duration: "35 min", order: 2 },
      { slug: "03-optimized-dockerfile", title: "လုံခြုံရေးမြှင့်တင်ထားသော အဆင့်ဆင့် Dockerfile ကို ရေးသားခြင်း", duration: "35 min", order: 3 },
      { slug: "04-github-actions-ci", title: "အလိုအလျောက် CI ပိုက်လိုင်းကို ပြင်ဆင်ခြင်း (Lint, Test, Security)", duration: "40 min", order: 4 },
      { slug: "05-registry-publish", title: "GitHub Container Registry (GHCR) သို့ ရုပ်ပုံများ တည်ဆောက်ခြင်းနှင့် ပို့ဆောင်ခြင်း", duration: "30 min", order: 5 },
      { slug: "06-provisioning-k3s", title: "ထုတ်လုပ်မှု K3s ဆာဗာကို စီစဉ်ပြင်ဆင်ခြင်း", duration: "40 min", order: 6 },
      { slug: "07-k8s-manifests", title: "ထုတ်လုပ်မှု Kubernetes ဖော်ပြချက်များကို ရေးသားခြင်း", duration: "45 min", order: 7 },
      { slug: "08-cd-automation", title: "GitHub Actions မှ K3s သို့ CD ဖြန့်ချိမှုများကို အလိုအလျောက်လုပ်ဆောင်ခြင်း", duration: "45 min", order: 8 },
      { slug: "09-domain-and-ssl", title: "စိတ္တဇ ဒိုမိန်း၊ DNS နှင့် အခမဲ့ အလိုအလျောက် SSL", duration: "30 min", order: 9 },
      { slug: "10-monitoring-celebration", title: "စောင့်ကြည့်ခြင်း၊ ကျန်းမာရေး သတိပေးချက်များနှင့် ပရောဂျက် ပြီးဆုံးခြင်း", duration: "30 min", order: 10 },
    ],
    featured: true,
    order: 12,
    hasFullContent: true,
  },
];